### ISSUE TITLE
MyParcel Belgium fatal error when activating 5.1.0

### ISSUE THREAD

**Issue by nieelu** [myparcelnl/woocommerce#1218]
### MyParcel plugin version

5.1.0

### WooCommerce version

9.5.1

### WordPress version

6.7.1

### PHP version

8.0

### What went wrong?

When activating the plugin after installation I get a fatal error:

[19-Dec-2024 20:26:56 UTC] PHP Fatal error: Uncaught Error: Failed opening required '/home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/composer/../myparcelnl/pdk/tests/functions.php' (include_path='.:/usr/share/php') in /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/composer/autoload_real.php:33 Stack trace: #0 /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/composer/autoload_real.php(37): {closure}() #1 /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/autoload.php(20): ComposerAutoloaderInitfb1e1ba16fea7c92c371f4bee202b272::getLoader() #2 /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/wc-myparcel-belgium.php(24): require('...') #3 /home/****-dev/htdocs/dev.****.be/wp-admin/includes/plugin.php(2387): include_once('...') #4 /home/****-dev/htdocs/dev.****.be/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape() #5 /home/****-dev/htdocs/dev.****.be/wp-admin/plugins.php(60): activate_plugin() #6 {main} thrown in /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/composer/autoload_real.php on line 33

### Reproduction steps

Install plugin (upload ZIP, release file on Github)
Activate
Fatal error

### Relevant log output

```shell
[19-Dec-2024 20:26:56 UTC] PHP Fatal error: Uncaught Error: Failed opening required '/home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/composer/../myparcelnl/pdk/tests/functions.php' (include_path='.:/usr/share/php') in /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/composer/autoload_real.php:33 Stack trace: #0 /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/composer/autoload_real.php(37): {closure}() #1 /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/autoload.php(20): ComposerAutoloaderInitfb1e1ba16fea7c92c371f4bee202b272::getLoader() #2 /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/wc-myparcel-belgium.php(24): require('...') #3 /home/****-dev/htdocs/dev.****.be/wp-admin/includes/plugin.php(2387): include_once('...') #4 /home/****-dev/htdocs/dev.****.be/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape() #5 /home/****-dev/htdocs/dev.****.be/wp-admin/plugins.php(60): activate_plugin() #6 {main} thrown in /home/****-dev/htdocs/dev.****.be/wp-content/plugins/wc-myparcel-belgium/vendor/composer/autoload_real.php on line 33
```

**Comment by nieelu** [comment]
Looks like the release was built with test mode (autoload-dev)?

**Comment by joerivanveen** [comment]
We are investigating what happened with the release and will work on a fix immediately.

**Comment by FreekVR** [comment]
We've fixed the underlying issue with github actions and released `5.2.0` which is otherwise unchanged but doesn't contain the dev deps. I've also pulled the assets for 5.1.0 so that it doesn't get installed accidentally.
