### ISSUE TITLE
WooCommerce 2.6 not supported (suggestion to drop support altogether)

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/woocommerce#617]
**Describe the bug**
WooCommerce MyParcel has compatibility classes in place to handle pre-WC3.0 (= non CRUD) data, most of the files in this folder:
https://github.com/myparcelnl/woocommerce/tree/develop/includes/compatibility

However, these exact compatibility classes crash due to incompatibility with WC2.X:

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to WPO\WC\MyParcel\Compatibility\Data::removeSerialization() must be an instance of WC_Data, instance of WC_Order given, called in /public_html/wp-content/plugins/woocommerce-myparcel/includes/compatibility/abstract-wc-data-compatibility.php on line 123 and defined in /public_html/wp-content/plugins/woocommerce-myparcel/includes/compatibility/abstract-wc-data-compatibility.php:231
> Stack trace:
> #0 /public_html/wp-content/plugins/woocommerce-myparcel/includes/compatibility/abstract-wc-data-compatibility.php(123): WPO\WC\MyParcel\Compatibility\Data::removeSerialization(Object(WC_Order), '_myparcel_shipm...', '')
> #1 /public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmypa-admin.php(521): WPO\WC\MyParcel\Compatibility\Data::get_meta(Object(WC_Order), '_myparcel_shipm...')
> #2 / in /public_html/wp-content/plugins/woocommerce-myparcel/includes/compatibility/abstract-wc-data-compatibility.php on line 231

This was function (/bug) introduced by 81067bd9565e169f4158ba717fe1d5bbb76f5711

A similar thing of compatibility check breaking compatibility happens with a call to `is_wp_version_compatible`. This function was introduced in WP5.2 but in your plugin it is used to check for WP4.7.

> PHP Fatal error:  Uncaught Error: Call to undefined function is_wp_version_compatible() in /public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmypa-admin.php:68
> Stack trace:
> #0 /public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmypa-admin.php(16): WCMYPA_Admin->__construct()
> #1 /public_html/wp-content/plugins/woocommerce-myparcel/woocommerce-myparcel.php(178): require_once('/home/deb96862/...')
> #2 /public_html/wp-content/plugins/woocommerce-myparcel/woocommerce-myparcel.php(214): WCMYPA->includes()
> #3 /public_html/wp-includes/class-wp-hook.php(286): WCMYPA->load_classes('')
> #4 /public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
> #5 /public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
> # in /public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmypa-admin.php on line 68

With the plugin in its current (relatively unstable) state, I would strongly recommend to drop compatibility for these older versions altogether (making WC3.0 + PHP4.9 minimum), to be able to do a bit of a cleanup in this code and use the WooCommerce CRUD functionality directly. This will make the plugin more performant as well as easier to maintain.

**Steps to reproduce this behaviour**
Install with WC2.6.14
Install on WP4.9

**Comment by RichardPerdaan** [comment]
Hi @Spreeuw,

From version 4.2.0 we have indicated that WC3.5.1 + PHP7.1 is the minimum.
this is also described in the readme.text

**Comment by Spreeuw** [comment]
@RichardPerdaan I think you may have misunderstood the purpose of this report.

You have a collection of compatibility classes _specifically_ in place for WC2.X
If you only support WC3.5.1+ that's all the more reason to drop those classes and stop using `WCX_Order` etc in favor of the official CRUD calls directly on the `$order` object.

Likewise, if you don't intend to support WP4.7, you should remove the legacy code in place to support it (and don't use a WP5.2 function to perform this check because it will crash on that very version).
