### ISSUE TITLE
Order with pickup but no pickup location crashes WooCommerce screens

### ISSUE THREAD

**Issue by EdieLemoine** [myparcelnl/woocommerce#757]
### Plugin version

4.8.0

### WooCommerce version

?

### WordPress version

5.8.2

### PHP version

7.3.33

### What went wrong?

Issue from original comment by @phemels: https://github.com/myparcelnl/woocommerce/issues/701#issuecomment-1004862961

### Reproduction steps

1. Have order with `delivery_type=pickup` but no `pickup_location` in dellivery options
2. Go to order grid or order itself
3. See entire page crashing down

### Relevant log output

```shell
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 109 van het bestand /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Adapter/DeliveryOptions/AbstractPickupLocationAdapter.php. Foutmelding: Uncaught TypeError: Return value of MyParcelNL\Sdk\src\Adapter\DeliveryOptions\AbstractPickupLocationAdapter::getCity() must be of the type string, null returned in /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Adapter/DeliveryOptions/AbstractPickupLocationAdapter.php:109
Stack trace:
#0 /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(345): MyParcelNL\Sdk\src\Adapter\DeliveryOptions\AbstractPickupLocationAdapter->getCity()
#1 /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(278): MyParcelNL\WooCommerce\includes\admin\OrderSettings->setPickupLocation()
#2 /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(152): MyParcelNL\WooCommerce\includes\admin\OrderSettings->setAllData()
#3 /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/includ
```

**Comment by EdieLemoine** [comment]
Should be solved after including a release of `myparcelnl/sdk` which includes myparcelnl/sdk#379

**Comment by RichardPerdaan** [comment]
The solution can be found in the following PR: myparcelnl/sdk#403
