### ISSUE TITLE
WordPress crashes after plugin install.

### ISSUE THREAD

**Issue by osenbruggen** [myparcelnl/woocommerce#900]
### Plugin version

4.14.0

### WooCommerce version

7.0.0

### WordPress version

6.0.3

### PHP version

8.1.12

### What went wrong?

Tried do install the plugin, when I activate I get critical error in WordPress.

### Reproduction steps

Install plugin

### Relevant log output

```shell
[Tue Nov 01 12:28:37.711831 2022] [proxy_fcgi:error] [pid 7283:tid 140185785222720] [client 46.129.0.154:58681] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Undefined constant MyParcelNL\\Sdk\\src\\Model\\Consignment\\AbstractConsignment::EXTRA_OPTION_DELIVERY_MONDAY in /export/home/groove.nl/htdocs/wp-content/plugins/woocommerce-myparcel/includes/admin/settings/class-wcmp-settings-data.php:60\nStack trace:\n#0 /export/home/groove.nl/htdocs/wp-content/plugins/woocommerce-myparcel/includes/admin/settings/class-wcmp-settings-data.php(17): WCMP_Settings_Data->__construct()\n#1 /export/home/groove.nl/htdocs/wp-content/plugins/woocommerce-myparcel/includes/admin/settings/class-wcmypa-settings.php(161): require_once('...')\n#2 /export/home/groove.nl/htdocs/wp-content/plugins/woocommerce-myparcel/includes/admin/settings/class-wcmypa-settings.php(11): WCMYPA_Settings->__construct()\n#3 /export/home/groove.nl/htdocs/wp-content/plugins/woocommerce-myparcel/woocommerce-myparcel.php(190): require_once('...')\n#4 /export/home/groove.nl/htdocs/wp-content/plugins/woocommerce-myparcel/woocommerce-myparcel.php(216): WCMYPA->includes...', referer: https://www2.groove.nl/wp-admin/plugins.php
```

**Comment by osenbruggen** [comment]
I tried both download and through the search plugin.

**Comment by osenbruggen** [comment]
I upgraded to WordPress 6.1 and uploaded the plugin again from Github and now it works.
