### ISSUE TITLE
Conflict with the woocommerce-follow-up-emails

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/woocommerce#99]
**The following error is visible inside the wc-myparcel log:**

2018-05-30T09:13:29+00:00 CRITICAL Uncaught Error: Cannot use string offset as an array in /home/deb58225/domains/be-slank.nl/public_html/wp-content/plugins/woocommerce-follow-up-emails/includes/sending/class-fue-sending-queue-item.php:155
Stack trace:
#0 /home/deb58225/domains/be-slank.nl/public_html/wp-content/plugins/woocommerce-follow-up-emails/includes/sending/class-fue-sending-scheduler.php(996): FUE_Sending_Queue_Item->add_note('The email "Revi...')
#1 /home/deb58225/domains/be-slank.nl/public_html/wp-content/plugins/woocommerce-follow-up-emails/includes/sending/class-fue-sending-scheduler.php(862): FUE_Sending_Scheduler->insert_email_order(Array, true)
#2 /home/deb58225/domains/be-slank.nl/public_html/wp-content/plugins/woocommerce-follow-up-emails/includes/addons/class-fue-addon-woocommerce-scheduler.php(1103): FUE_Sending_Scheduler::queue_email(Array, Object(FUE_Email))
#3 /home/deb58225/domains/be-slank.nl/public_html/wp-content/plugins/woocommerce-follow-up-emails/includes/addons/class-fue-addon-woocommerce-scheduler.php(232): FUE_

case: 00346375

**Comment by RichardPerdaan** [comment]
Myparcel sets all orders after export to completed (an option in the
myparcel settings). So when the status changed manually of an
order to completed (without exporting) the error is visible. So it was not a MyParcel conflict with woocommerce or the woocommerce-follow-up-emails.
